apiVersion: v1
kind: Route
metadata:
  name: route-dev-webapp
spec:
  path: /
  to:
    kind: Service
    name: dev-webapp
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  
